version: '3.8'

services:
  app:
    container_name: students_api
    image: flaskapp:latest
    build: .
    ports:
    - '8000:8000'
    restart: always
    environment:
      FLASK_APP: api.py
      FLASK_ENVIRONMENT: development
      DB_USERNAME: "devops"
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_NAME: "student"
    networks:
      - students_api

networks:
  students_api:
    name: students_api_network
