apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  namespace: flaskapp
spec:
  selector:
    name: flaskapp
  ports:
  - port: 8000
    name: app-service-port
    targetPort: flask-port
    protocol: TCP
    