apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: flaskapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: flaskapp
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"
    ports:
      - containerPort: 3306
        name: mysql-port
    volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
    env:
      - name: MYSQL_USER
        value: devops
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: flaskapp-secret
            key: mysql_password
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: flaskapp-secret
            key: mysql_root_password
      - name: MYSQL_DATABASE
        valueFrom:
          configMapKeyRef:
            name: flaskapp-configmap
            key: mysql_database
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim
  